### ISSUE TITLE
not compatible with blender 2.8

### ISSUE THREAD

**Issue by benjamindahl** [ScottMichaud/blender-makecoplanar#1]
![Bildschirmfoto 2019-10-09 um 16 45 46](https://user-images.githubusercontent.com/2698024/66492210-5144ff80-eab4-11e9-9446-ce59ce829701.png)
Any plans for updates?

**Comment by ScottMichaud** [comment]
I wasn't aware that anyone used it, and I haven't needed it myself recently. I could certainly look into it.

**Comment by ScottMichaud** [comment]
Fix was simple. Add-on works, but it's not (and has never been) a good user experience.

**Comment by ScottMichaud** [comment]
Note that you'll want to follow the normal 2.80 install instructions, not the readme. I'll update that soon.

So... remove any previous instance of Mesh: Make Coplanar by the Remove button in its entry in Blender Preferences and then use the "Install..." button to install mesh_makecoplanar.py from wherever you downloaded it.

**Comment by benjamindahl** [comment]
Ok. Nice. I'll try it. Cheers.

**Comment by ScottMichaud** [comment]
Updated README.md with the new install and usage instructions.

**Comment by ScottMichaud** [comment]
It's been two weeks so I'll assume everything is good. Let me know if this needs to be followed-up on.
